[tool.poetry]
name = "multiocr"
version = "0.1.0"
description = ""
authors = ["Aravindh <32878238+s-aravindh@users.noreply.github.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
